services:
  import-module:
    image: dcm/import-module:latest
    container_name: import-module
    environment:
      - USE_TEST_PLUGIN=1
    volumes:
      - file_storage:/file_storage
  object-validator:
    image: dcm/object-validator:latest
    container_name: object-validator
    volumes:
      - file_storage:/file_storage
  ip-builder:
    image: dcm/ip-builder:latest
    container_name: ip-builder
    environment:
      - USE_OBJECT_VALIDATOR=0
    volumes:
      - file_storage:/file_storage
  sip-builder:
    image: dcm/sip-builder:latest
    container_name: sip-builder
    volumes:
      - file_storage:/file_storage
  transfer-module:
    image: dcm/transfer-module:latest
    container_name: transfer-module
    environment:
      - LOCAL_TRANSFER=1
      - REMOTE_DESTINATION=/file_storage/remote
    volumes:
      - file_storage:/file_storage
  job-processor:
    image: dcm/job-processor:latest
    container_name: job-processor
    environment:
      - IMPORT_MODULE_HOST=http://import-module
      - IP_BUILDER_HOST=http://ip-builder
      - OBJECT_VALIDATOR_HOST=http://object-validator
      - SIP_BUILDER_HOST=http://sip-builder
      - TRANSFER_MODULE_HOST=http://transfer-module
      - BACKEND_HOST=http://backend
      - ORCHESTRATION_REGISTRY_ADAPTER=http
      - 'ORCHESTRATION_REGISTRY_SETTINGS={"url": "http://report-db"}'
  backend:
    image: dcm/backend:latest
    container_name: backend
    environment:
      - ORCHESTRATION_PROCESSES=5
      - JOB_PROCESSOR_HOST=http://job-processor
      - ROSETTA_AUTH_FILE=/app/stub_auth
      - ARCHIVE_API_BASE_URL=http://rosetta-stub
      - REPORT_DATABASE_ADAPTER=http
      - 'REPORT_DATABASE_SETTINGS={"url": "http://report-db"}'
    ports:
      - 8085:80
  report-db:
    image: dcm/key-value-store:latest
    container_name: report-db
  rosetta-stub:
    image: dcm/rosetta-stub:latest
    container_name: rosetta-stub
    environment:
      - ROSETTA_STUB_OUT=/file_storage/archive
    volumes:
      - file_storage:/file_storage
volumes:
  file_storage:
    external: True
    name: dcm_file_storage
