# base image
FROM python:3.10-alpine

# python
WORKDIR /app
RUN pip install --upgrade \
    --extra-index-url https://zivgitlab.uni-muenster.de/api/v4/projects/9020/packages/pypi/simple \
    "dcm-common[db, services]>=3.14.1,<4.0.0"
RUN pip install gunicorn

# create app-file
COPY ./key_value_store.py /app/app.py

# run
ENV WEB_CONCURRENCY=5
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:80 --workers 1 --threads ${WEB_CONCURRENCY} app:app"]
